# Generated by Django 3.2.6 on 2021-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.TextField(blank=True, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='town',
            field=models.TextField(blank=True, null=True, verbose_name='town'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
