# Generated by Django 4.0.3 on 2022-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_content_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
