# Generated by Django 4.0.3 on 2022-03-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_upload',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_date',
        ),
    ]
