# Generated by Django 4.0.3 on 2022-03-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
