# Generated by Django 4.0.3 on 2022-03-21 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_remove_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
