# Generated by Django 4.0.3 on 2022-03-23 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_note_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
