# Generated by Django 4.0.3 on 2022-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
